[Standard]
number = true 
statusBar = true
syntax = true
tabStop = 2
autoCloseParen = true
autoIndent = true
defaultCursor = "block"
normalModeCursor = "block"
insertModeCursor = "ibeam"

[StatusBar]
mode = true
chanedMark = true
line = true
column = true
encoding = true
language = true
directory = true
