[Standard]

theme = "dark"

number = true

currentNumber = true

cursorLine = false

statusBar = true

tabLine = true

syntax = true

indentationLines = true

tabStop = 2

autoCloseParen = true

autoIndent = true

defaultCursor = "blinkBlock"

normalModeCursor = "blinkBlock"

insertModeCursor = "blinkIbeam"

autoSave = false

autoSaveInterval = 5

liveReloadOfConf = false

realtimeSearch = true

popUpWindowInExmode = true

replaceTextHighlight = true

highlightPairOfParen = true

autoDeleteParen = true

systemClipboard = true

highlightFullWidthSpace = true

highlightTrailingSpaces = true

highlightCurrentWord = true

[BuildOnSaveSettings]

buildOnSave = false

# workspaceRoot = "/home/fox/git/moe"

# command = "cd /home/fox/git/moe && nimble build"

[TabLine]

allBuffer = false

[StatusBar]

mode = true

chanedMark = true

line = true

column = true

encoding = true

language = true

directory = true

multipleStatusBar = true

gitbranchName = true

showGitInactive = false

[WorkSpace]

useBar = false

[Highlight]

reservedWord = ["TODO", "WIP", "NOTE"]

[Filer]

showIcons = true

[Theme]

baseTheme = "dark"

editorBg = "default"

lineNum = "gray54"

lineNumBg = "default"

currentLineNum = "teal"

currentLineNumBg = "default"

statusBar = "white"

statusBarBg = "blue"

statusBarMode = "black"

statusBarModeBg = "white"

statusBarNormalMode = "white"

statusBarNormalModeBg = "blue"

statusBarModeNormalMode = "black"

statusBarModeNormalModeBg = "white"

statusBarNormalModeInactive = "blue"

statusBarNormalModeInactiveBg = "white"

statusBarInserMode = "white"

statusBarInserModeBg = "blue"

statusBarModeInserMode = "black"

statusBarModeInserModeBg = "white"

statusBarInsertModeInactive = "blue"

statusBarInsertModeInactiveBg = "white"

statusBarVisualMode = "white"

statusBarVisualModeBg = "blue"

statusBarModeVisualMode = "black"

statusBarModeVisualModeBg = "white"

statusBarVisualModeInactive = "blue"

statusBarVisualModeInactiveBg = "white"

statusBarReplaceMode = "white"

statusBarReplaceModeBg = "blue"

statusBarModeReplaceMode = "black"

statusBarModeReplaceModeBg = "white"

statusBarReplaceModeInactive =  "blue"

statusBarReplaceModeInactiveBg = "white"

statusBarFilerMode = "white"

statusBarFilerModeBg = "blue"

statusBarModeFilerMode = "black"

statusBarModeFilerModeBg = "white"

statusBarFilerModeInactive = "blue"

statusBarFilerModeInactiveBg = "white"

statusBarExMode = "black"

statusBarExModeBg = "white"

statusBarModeExMode = "black"

statusBarModeExModeBg = "white"

statusBarExModeInactive = "blue"

statusBarExModeInactiveBg = "white"

tab = "white"

tabBg = "default"

currentTab = "white"

currentTabBg = "blue"

commandBar = "gray100"

commandBarBg = "default"

errorMessage = "red"

errorMessageBg = "default"

searchResult = "default"

searchResultBg = "red"

visualMode = "gray100"

visualModeBg = "purple_1"

defaultCharactorColor = "gray100"

gtKeywordColor = "seaGreen1_2"

gtStringLitColor = "purple_1"

gtDecNumberColor = "aqua"

gtCommentColor = "gray"

gtLongCommentColor = "gray"

gtWhitespaceColor = "gray100"

currentFile = "gray100"

currentFileBg = "teal"

file = "gray100"

fileBg = "default"

dir = "blue"

dirBg = "default"

pcLink = "teal"

pcLinkBg = "default"

popUpWindow = "gray100"

popUpWindowBg = "black"

popUpWinCurrentLine = "blue"

popUpWinCurrentLineBg = "black"

replaceText = "default"

replaceTextBg = "red"

currentWordBg = "gray"

highlightFullWidthSpace =  "red"

highlightFullWidthSpaceBg = "red"

highlightTrailingSpaces = "red"

highlightTrailingSpacesBg = "red"

workSpaceBar = "white"

workSpaceBarBg = "blue"

reservedWord = "deepPink1_1" 

reservedWordBg = "black" 
