[Standard]

theme = "vivid"

number = true 

currentNumber = true 

cursorLine = false

statusBar = true

tabLine = true

syntax = true

tabStop = 2

autoCloseParen = true

autoIndent = true

defaultCursor = "block"

normalModeCursor = "block"

insertModeCursor = "ibeam"

[StatusBar]

mode = true

chanedMark = true

line = true

column = true

encoding = true

language = true

directory = true

[Theme]

baseTheme = "dark"

editorBg = "default"

lineNum = "gray54"

lineNumBg = "default"

currentLineNum = "teal"

currentLineNumBg = "default"

statusBar = "white"

statusBarBg = "blue"

statusBarMode = "black"

statusBarModeBg = "white"

tab = "white"

tabBg = "default"

currentTab = "white"

currentTabBg = "blue"

commandBar = "gray100"

commandBarBg = "default"

errorMessage = "red"

errorMessageBg = "default"

searchResult = "default"

searchResultBg = "red"

visualMode = "gray100"

visualModeBg = "purple_1"

defaultCharactorColor = "gray100"

gtKeywordColor = "seaGreen1_2"

gtStringLitColor = "purple_1"

gtDecNumberColor = "aqua"

gtCommentColor = "white"

gtLongCommentColor = "white"

gtWhitespaceColor = "gray100"

currentFile = "gray100"

currentFileBg = "teal"

file = "gray100"

fileBg = "default"

dir = "blue"

dirBg = "default"

pcLink = "teal"

pcLinkBg = "default"
