[Standard]

theme = "dark"

number = true

currentNumber = true

cursorLine = false

statusBar = true

tabLine = true

syntax = true

indentationLines = true

tabStop = 2

autoCloseParen = true

autoIndent = true

ignorecase = true

smartcase = true

disableChangeCursor = false

defaultCursor = "blinkBlock"

normalModeCursor = "blinkBlock"

insertModeCursor = "blinkIbeam"

autoSave = false

autoSaveInterval = 5

liveReloadOfConf = false

incrementalSearch = true

popUpWindowInExmode = true

autoDeleteParen = true

systemClipboard = true

smoothScroll = true

smoothScrollSpeed = 15

[BuildOnSave]

enable = false

# workspaceRoot = "/home/fox/git/moe"

# command = "cd /home/fox/git/moe && nimble build"

[TabLine]

allBuffer = false

[StatusBar]

multipleStatusBar = true

merge = false

mode = true

filename = true

chanedMark = true

line = true

column = true

encoding = true

language = true

directory = true

gitbranchName = true

showGitInactive = false

showModeInactive = false

[WorkSpace]

workSpaceLine = false

[Highlight]

reservedWord = ["TODO", "WIP", "NOTE"]

replaceText = true

pairOfParen = true

fullWidthSpace = true

trailingSpaces = true

currentWord = true

[AutoBackup]

enable = true

# 10 second
idleTime = 10

# 5 minute
interval = 5

# backupDir = "/home/fox/Nim"

dirToExclude = ["/etc"]

[QuickRun]

saveBufferWhenQuickRun = true

# command = "nimble build"

# 30 second
timeout = 30

# nimAdvancedCommand = "js"

# ClangOptions = "-Wall"

# CppOptions = "-Wall"

# NimOptions = "--debugger:native"

# shOptions = "-c"

# bashOptions = "-c"

[Notification]

screenNotifications = true

logNotifications = true

autoBackupScreenNotify = true

autoBackupLogNotify = true

autoSaveScreenNotify = true

autoSaveLogNotify = true

yankScreenNotify = true

yankLogNotify = true

deleteScreenNotify = true

deleteLogNotify = true

saveScreenNotify = true

saveLogNotify = true

workspaceScreenNotify = true

workspaceLogNotify = true

quickRunScreenNotify = true

quickRunLogNotify = true

buildOnSaveScreenNotify = true

buildOnSaveLogNotify = true

filerScreenNotify = true

filerLogNotify = true

restoreScreenNotify = true

restoreLogNotify = true

[Filer]

showIcons = true

[Autocomplete]

enable = true

[Debug.WindowNode]
enable = true
currentWindow = true
index = true
windowIndex = true
bufferIndex = true
parentIndex = true
childLen = true
splitType = true
haveCursesWin = true
y = true
x = true
h = true
w = true
currentLine = true
currentColumn = true
expandedColumn = true
cursor = true

[Debug.BufferStatus]
enable = true
bufferIndex = true
path = true
openDir = true
currentMode = true
prevMode = true
language = true
encoding = true
countChange = true
cmdLoop = true
lastSaveTime = true
bufferLen = true

[Theme]

baseTheme = "dark"

editorBg = "default"
lineNum = "gray54"
lineNumBg = "default"
currentLineNum = "teal"
currentLineNumBg = "default"
# statsu bar
statusBarNormalMode = "white"
statusBarNormalModeBg = "blue"
statusBarModeNormalMode = "black"
statusBarModeNormalModeBg = "white"
statusBarNormalModeInactive = "blue"
statusBarNormalModeInactiveBg = "white"

statusBarInsertMode = "white"
statusBarInsertModeBg = "blue"
statusBarModeInsertMode = "black"
statusBarModeInsertModeBg = "white"
statusBarInsertModeInactive = "blue"
statusBarInsertModeInactiveBg = "white"

statusBarVisualMode = "white"
statusBarVisualModeBg = "blue"
statusBarModeVisualMode = "black"
statusBarModeVisualModeBg = "white"
statusBarVisualModeInactive = "blue"
statusBarVisualModeInactiveBg = "white"

statusBarReplaceMode = "white"
statusBarReplaceModeBg = "blue"
statusBarModeReplaceMode = "black"
statusBarModeReplaceModeBg = "white"
statusBarReplaceModeInactive = "blue"
statusBarReplaceModeInactiveBg = "white"

statusBarFilerMode = "white"
statusBarFilerModeBg = "blue"
statusBarModeFilerMode = "black"
statusBarModeFilerModeBg = "white"
statusBarFilerModeInactive = "blue"
statusBarFilerModeInactiveBg = "white"

statusBarExMode = "white"
statusBarExModeBg = "blue"
statusBarModeExMode = "black"
statusBarModeExModeBg = "white"
statusBarExModeInactive = "blue"
statusBarExModeInactiveBg = "white"

statusBarGitBranch = "white"
statusBarGitBranchBg = "blue"

# tab line
tab = "white"
tabBg = "default"
currentTab = "white"
currentTabBg = "blue"

# command  bar
commandBar = "gray100"
commandBarBg = "default"

# error message
errorMessage = "red"
errorMessageBg = "default"

# search result highlighting
searchResult = "default"
searchResultBg = "red"

# selected area in visual mode
visualMode = "gray100"
visualModeBg = "purple_1"

# color scheme
defaultChar = "white"
gtKeyword = "skyBlue1"
gtFunctionName = "gold1"
gtBoolean = "yellow"
gtStringLit = "yellow"
gtSpecialVar = "green"
gtBuiltin = "yellow"
gtDecNumber = "aqua"
gtComment = "gray"
gtLongComment = "gray"
gtWhitespace = "gray"
gtPreprocessor = "green"

# filer mode
currentFile = "gray100"
currentFileBg = "teal"
file = "gray100"
fileBg = "default"
dir = "blue"
dirBg = "default"
pcLink = "teal"
pcLinkBg = "default"

# pop up window
popUpWindow = "gray100"
popUpWindowBg = "black"
popUpWinCurrentLine = "blue"
popUpWinCurrentLineBg = "black"

# replace text highlighting
replaceText = "default"
replaceTextBg = "red"

# pair of paren highlighting
parenText = "default"
parenTextBg = "white"

# highlight other uses current word
currentWord = "default"
currentWordBg = "gray"

# highlight full width space
highlightFullWidthSpace = "red"
highlightFullWidthSpaceBg = "red"

# highlight trailing spaces
highlightTrailingSpaces = "red"
highlightTrailingSpacesBg = "red"

# work space bar
workSpaceBar = "white"
workSpaceBarBg = "blue"

# highlight reserved words
reservedWord = "white"
reservedWordBg = "gray"

# configuration mode
currentSetting = "gray100"
currentSettingBg = "teal"
