language: c
compiler:
  - gcc
services:
  - xvfb
before_install:
  - sudo ln -sf /lib/x86_64-linux-gnu/libncursesw.so.5.9 /usr/lib/x86_64-linux-gnu/libncursesw.so
  - export CHOOSENIM_NO_ANALYTICS=1
  # Error occur => curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.
  #- curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
  - wget https://nim-lang.org/choosenim/init.sh
  - sh init.sh -y
  - export PATH=~/.nimble/bin:$PATH
  - echo "export PATH=~/.nimble/bin:$PATH" >> ~/.profile
  - choosenim stable
  # Manual install xclip v0.13
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/x/xclip/xclip_0.13-1_amd64.deb
  - sudo dpkg -i xclip_0.13-1_amd64.deb
  # Integration test tools
  - sudo sh -c "`curl -L https://raw.githubusercontent.com/rylnd/shpec/master/install.sh`"
  - sudo apt-get update && sudo apt-get install -y abduco
before_script:
  - set -e
  - export PATH=$(pwd)/nim/bin:$(pwd):$PATH
script:
  - nimble refresh
  - yes | nimble test --verbose
  - nimble install --verbose
  - shpec ./shpec.sh
