language: c
compiler:
  - gcc
before_install:
  - sudo ln -sf /lib/x86_64-linux-gnu/libncursesw.so.5.9 /usr/lib/x86_64-linux-gnu/libncursesw.so
  - export CHOOSENIM_NO_ANALYTICS=1
  - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
  - sh init.sh -y
  - export PATH=~/.nimble/bin:$PATH
  - echo "export PATH=~/.nimble/bin:$PATH" >> ~/.profile
  - choosenim stable
before_script:
  - set -e
  - export PATH=$(pwd)/nim/bin:$(pwd):$PATH
script:
  - nimble refresh
  - yes | nimble test --verbose
  - nimble install --verbose
