language: c
compiler:
  - gcc
services:
  - xvfb
before_install:
  - sudo ln -sf /lib/x86_64-linux-gnu/libncursesw.so.5.9 /usr/lib/x86_64-linux-gnu/libncursesw.so
  - export CHOOSENIM_NO_ANALYTICS=1
  # Error occur => curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.
  #- curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
  - wget https://nim-lang.org/choosenim/init.sh
  - sh init.sh -y
  - export PATH=~/.nimble/bin:$PATH
  - echo "export PATH=~/.nimble/bin:$PATH" >> ~/.profile
  - choosenim stable
before_script:
  - set -e
  - export PATH=$(pwd)/nim/bin:$(pwd):$PATH
script:
  - sudo apt-get install xclip
  - nimble refresh
  - yes | nimble test --verbose
  - nimble install --verbose
